### ISSUE TITLE
Arris TG2492LG-ZG login failure

### ISSUE THREAD

**Issue by mbugert** [ties/compal_CH7465LG_py#21]
Hi @ties,

downstream in the connectbox-prometheus project, a log in issue with an Arris TG2492LG-ZG modem cropped up, see https://github.com/mbugert/connectbox-prometheus/issues/3. This is the device:  https://tweakers.net/pricewatch/789051/ziggo-connect-box/specificaties/
From the outside it looks compatible :laughing:.

Relevant bits of the stacktrace:
```
Exception happened during processing of request from ('172.17.0.1', 41560)

Traceback (most recent call last):
  [...]

  File "/usr/local/lib/python3.8/site-packages/connectbox_prometheus-0.2.6-py3.8.egg/connectbox_exporter/connectbox_exporter.py", line 58, in collect

    connectbox.login()

  File "/usr/local/lib/python3.8/site-packages/compal/__init__.py", line 202, in login

    if res.headers["Location"].endswith("common_page/Access-denied.html"):

  File "/usr/local/lib/python3.8/site-packages/requests/structures.py", line 54, in __getitem__

    return self._store[key.lower()][1]

KeyError: 'location'

----------------------------------------

ERROR:compal:Was not redirected to login page: concurrent session?
```

We would need someone who owns this device to confirm and possibly fix the issue. Maybe one of the guys/girls who +1'd the downstream issue is willing to step in?  @guyke01 @Metrac @jacekjaros

**Comment by jacekjaros** [comment]
Hi @mbugert,

I'm afraid that my python skills are not good enough to do this. If problem is only lack of dev environment i can provide vm connected to Arris box - if this help anyhow please just ping me.

best regards,
Jacek

**Comment by ties** [comment]
Hi @mbugert,

That's a good question!

I've heard about that modem but do not personally have access to it. It is visually very similar but as far as I know it has a different software stack.

It would be great to try if either https://github.com/billimek/SB6183-stats-for-influxdb or https://github.com/andrewfraley/arris_cable_modem_stats works with it. Often they just change the skin of the modems.

@jacekjaros can you take a screenshot of the 'network' tab of google chrome when loading the web interface? That is likely enough to confirm that it is indeed different.

kind regards,
Ties
