### ISSUE TITLE
CH7465VF: Login failed for unknown reason!

### ISSUE THREAD

**Issue by probonopd** [ties/compal_CH7465LG_py#43]
With a CH7465 originally from Unitymedia that was updated by the provider and now identifies as 
![{2B849AC7-42E8-49A8-9EFF-96AA9B45C239}](https://github.com/user-attachments/assets/c005871c-550f-49bc-a2fa-e2d1a5338560)
 there is a [nasty bug](https://forum.vodafone.de/t5/Ger%C3%A4te/Router-CH7465VF-schaltet-WLAN-seit-einiger-Zeit-immer-wieder-an/td-p/3228814) that WLAN is switched on after power cycling the device, despite it was explicitly disabled.

I would like to use this script to automate WLAN to be switched off. This is my script so far:

```
import os
import time
from compal import *

modem = Compal('192.168.0.1', 'adminpassword')
modem.login()
```

However, when I run it with `python -vi  compal\wlanoff.py` I get:

```
INFO:compal:302 [http://192.168.0.1/] => '../common_page/login.html' [token: 1413005568]
INFO:compal:302 [http://192.168.0.1/xml/setter.xml] => '../common_page/login.html' [token: 485559040]
Traceback (most recent call last):
  File "C:\Users\User\compal\wlanoff.py", line 6, in <module>
    modem.login()
  File "C:\Users\User\compal\Lib\site-packages\compal\__init__.py", line 242, in login
    raise ValueError("Login failed for unknown reason!")
ValueError: Login failed for unknown reason!
```

Making the changes suggested in

* https://github.com/ties/compal_CH7465LG_py/issues/39

does not seem to work for me, as I then get

```
INFO:compal:302 [http://192.168.0.1/] => '../common_page/login.html' [token: 2912051456]
Traceback (most recent call last):
  File "C:\Users\User\compal\wlanoff.py", line 6, in <module>
    modem.login()
  File "C:\Users\User\compal\Lib\site-packages\compal\__init__.py", line 255, in login
    raise ValueError("No valid session-Id received! Wrong password?")
ValueError: No valid session-Id received! Wrong password?
```

**Comment by probonopd** [comment]
Update:

With

```
import os
import time
from compal import *

modem = Compal("192.168.0.1", username="admin", key="adminpassword", send_token=False, send_hash=True)
modem.login()

# Switch wireless networks off
wifi = WifiSettings(modem)
new_settings = wifi.wifi_settings
new_settings.band_mode=4 # 3 = on, 4 = off
wifi.update_wifi_settings(new_settings)
modem.logout()
```

it works. Maybe this helps someone.

Thanks for this script!
